# Generated by Django 6.0.3 on 2026-03-22 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_order_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('PLANNED', 'Planned'), ('PLACED', 'Placed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('POD_PENDING', 'POD Pending'), ('BILLED', 'Billed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('job_date', models.DateTimeField(auto_now_add=True)),
                ('customer_email', models.CharField(blank=True, max_length=200)),
                ('customer_contact_no', models.CharField(blank=True, max_length=20)),
                ('customer_client', models.CharField(blank=True, max_length=200)),
                ('customer_job_no', models.CharField(blank=True, max_length=50)),
                ('movement_type', models.CharField(choices=[('EXPORT', 'Export'), ('IMPORT', 'Import'), ('EMPTY', 'Empty'), ('LOCAL', 'Local')], default='EXPORT', max_length=10)),
                ('movement_for', models.CharField(choices=[('CALYX', 'CALYX'), ('OTHER', 'Other')], default='CALYX', max_length=10)),
                ('move_by', models.CharField(choices=[('ON_WHEEL', 'On Wheel'), ('LCL', 'LCL')], default='ON_WHEEL', max_length=10)),
                ('service_type', models.CharField(choices=[('LOCAL', 'Local'), ('EXIM', 'EXIM'), ('LONG_HAUL', 'Long Haul')], default='LOCAL', max_length=15)),
                ('stuffing_date', models.DateField(blank=True, null=True)),
                ('no_of_trailers', models.PositiveIntegerField(default=1)),
                ('gross_weight_mt', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('offered_freight_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adv_receipt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_day', models.PositiveIntegerField(default=0)),
                ('load_preference', models.CharField(choices=[('ONE_TIME', 'One Time'), ('REGULAR', 'Regular')], default='ONE_TIME', max_length=10)),
                ('reporting_datetime', models.DateTimeField(blank=True, null=True)),
                ('cut_off_datetime', models.DateTimeField(blank=True, null=True)),
                ('do_validity_datetime', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('customer_expectation', models.TextField(blank=True)),
                ('cn_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_orders', to='masters.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_orders', to='masters.customer')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders_destination', to='masters.location')),
                ('freight_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders', to='masters.freighttype')),
                ('lane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders', to='masters.lane')),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders', to='masters.materialtype')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders_origin', to='masters.location')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_job_orders', to=settings.AUTH_USER_MODEL)),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_job_orders', to=settings.AUTH_USER_MODEL)),
                ('service_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders', to='masters.serviceroute')),
                ('stuffing_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders_stuffing', to='masters.location')),
                ('truck_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders', to='masters.trucktype')),
            ],
            options={
                'verbose_name': 'Job Order',
                'verbose_name_plural': 'Job Orders',
                'ordering': ['-job_date'],
            },
        ),
        migrations.CreateModel(
            name='JobCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.cancellationreason')),
                ('job_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='jobs.joborder')),
            ],
            options={
                'verbose_name': 'Job Cancellation',
                'verbose_name_plural': 'Job Cancellations',
            },
        ),
    ]
