# Generated by Django 6.0.3 on 2026-03-22 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lane',
            name='location_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lanes_location_1', to='masters.location'),
        ),
        migrations.AddField(
            model_name='lane',
            name='location_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lanes_location_2', to='masters.location'),
        ),
    ]
