# Generated by Django 6.0.3 on 2026-03-22 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_kmr_hmr', models.CharField(blank=True, max_length=30)),
                ('no_running_from', models.DateTimeField()),
                ('alternate_vehicle_no', models.CharField(blank=True, max_length=20)),
                ('rent_applicable', models.BooleanField(default=False)),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reason_for_not_running', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.notrunningreason')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.vehicle')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.vendor')),
            ],
            options={
                'verbose_name_plural': 'Trailer Attendances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrailerPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_job_no', models.CharField(blank=True, max_length=50)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exp_reporting_datetime', models.DateTimeField(blank=True, null=True)),
                ('exp_trip_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('cut_off_datetime', models.DateTimeField(blank=True, null=True)),
                ('do_validity_datetime', models.DateTimeField(blank=True, null=True)),
                ('special_request', models.TextField(blank=True)),
                ('planned_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.branch')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='jobs.joborder')),
                ('planned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.vehicle')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.vendor')),
            ],
            options={
                'ordering': ['-planned_at'],
            },
        ),
        migrations.CreateModel(
            name='TrailerPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_datetime', models.DateTimeField(blank=True, null=True)),
                ('trip_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('exp_job_complete_datetime', models.DateTimeField(blank=True, null=True)),
                ('cut_off_datetime', models.DateTimeField(blank=True, null=True)),
                ('do_validity_datetime', models.DateTimeField(blank=True, null=True)),
                ('trip_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empty_running_kmr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('veh_start_state', models.CharField(blank=True, max_length=100)),
                ('veh_start_city', models.CharField(blank=True, max_length=100)),
                ('driver_mobile_no', models.CharField(blank=True, max_length=15)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('dl_no', models.CharField(blank=True, max_length=30)),
                ('diesel_litres', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('diesel_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('diesel_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trailer_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trip_advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trip_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('load_type', models.CharField(blank=True, choices=[('CARGO', 'Cargo'), ('CONTAINER', 'Container')], max_length=20)),
                ('container_no_1', models.CharField(blank=True, max_length=20)),
                ('container_size_1', models.CharField(blank=True, max_length=5)),
                ('container_no_2', models.CharField(blank=True, max_length=20)),
                ('container_size_2', models.CharField(blank=True, max_length=5)),
                ('customer_job_no', models.CharField(blank=True, max_length=50)),
                ('tracking_through', models.CharField(blank=True, choices=[('ABR', 'ABR'), ('INTUGINE', 'Intugine'), ('SIM', 'SIM Tracking'), ('MANUAL', 'Manual')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.branch')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.driver')),
                ('engaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engaged_placements', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='jobs.joborder')),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_placements', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.vehicle')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.vendor')),
                ('planning', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement', to='operations.trailerplanning')),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
    ]
