# Generated by Django 6.0.3 on 2026-03-22 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('masters', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_type', models.CharField(choices=[('DIGITAL', 'Digital POD'), ('PHYSICAL', 'Physical POD')], max_length=10)),
                ('file', models.FileField(upload_to='pods/%Y/%m/')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='jobs.joborder')),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='operations.trailerplacement')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proof of Delivery',
                'verbose_name_plural': 'Proofs of Delivery',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_number', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('is_current', models.BooleanField(default=False)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs_from', to='masters.location')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='jobs.joborder')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='operations.trailerplacement')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs_to', to='masters.location')),
            ],
            options={
                'ordering': ['placement', 'leg_number'],
                'unique_together': {('placement', 'leg_number')},
            },
        ),
        migrations.CreateModel(
            name='LegStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_YET_START', 'Not Yet Start'), ('LOADING', 'Loading'), ('IN_TRANSIT', 'In Transit'), ('UNLOADING', 'Unloading'), ('WAITING_DOC', 'Waiting For Document'), ('WAITING_STUFF', 'Waiting For Stuffing'), ('WAITING_DESTUFF', 'Waiting For De-Stuffing'), ('REACHED', 'Reached'), ('OUT', 'Out'), ('TRIP_STARTED', 'Trip Started'), ('TRAILER_CHANGE', 'Trailer Change'), ('DRIVER_CHANGE', 'Driver Change'), ('MOBILE_CHANGE', 'Mobile Change'), ('JOB_COMPLETED', 'Job Completed'), ('JOB_COMP_PNR', 'Job Completed – Next PNR Movement')], max_length=20)),
                ('status_datetime', models.DateTimeField()),
                ('remarks', models.TextField(blank=True)),
                ('gps_location', models.CharField(blank=True, max_length=255)),
                ('is_other_info', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='tracking.vehicleleg')),
            ],
            options={
                'ordering': ['-status_datetime'],
            },
        ),
    ]
